import {
  ArcOutline,
  FullFilled,
  FullOutline,
  HalfFilledV1,
  HalfFilledV2,
  HalfOutline,
  QuarterFilled,
} from "./Shapes";
import { Colors, ShapeConfig } from "./types";

// Randomize shapes around the screen
const home: ShapeConfig[] = [
  {
    icon: <HalfFilledV1 color={Colors.Purple} />,
    bottom: 8,
    left: 30,
    width: 10,
    lag: 1,
  },
  {
    icon: <HalfOutline color={Colors.Purple} />,
    bottom: 9,
    left: 33,
    width: 12,
    lag: 2,
    rotate: -45,
    opacity: 0.6,
  },
  {
    icon: <HalfFilledV2 color={Colors.Red} />,
    top: 43,
    left: 20,
    width: 13,
    lag: 1,
  },
  {
    icon: <ArcOutline color={Colors.Beige} />,
    top: 41,
    left: 22,
    width: 13,
    lag: 3,
  },
  {
    icon: <QuarterFilled color={Colors.Pink} />,
    top: 24,
    left: 40,
    width: 8,
    lag: 4,
  },
  {
    icon: <FullOutline color={Colors.Red} />,
    bottom: 35,
    left: 53,
    width: 15,
    lag: 4,
  },
  {
    icon: <FullFilled color={Colors.Orange} />,
    top: 32,
    right: 15,
    width: 10,
    lag: 1,
  },
  {
    icon: <HalfOutline color={Colors.Orange} />,
    top: 42,
    right: 16,
    width: 12,
    lag: 4,
    rotate: 34,
  },
  {
    icon: <HalfFilledV2 color={Colors.Teal} />,
    bottom: 22,
    right: 20,
    width: 12,
    lag: 1,
    rotate: 40,
  },
  {
    icon: <FullOutline color={Colors.Teal} />,
    bottom: 18,
    right: 24,
    width: 8,
    lag: 4,
    rotate: 40,
  },
  {
    icon: <HalfOutline color={Colors.Pink} />,
    bottom: 18,
    left: 10,
    width: 10,
    lag: 4,
    rotate: 40,
  },
];

const about: ShapeConfig[] = [
  {
    icon: <HalfFilledV1 color={Colors.Orange} />,
    bottom: 8,
    left: 38,
    width: 8,
    lag: 1,
    rotate: 58,
  },
  {
    icon: <HalfOutline color={Colors.Orange} />,
    bottom: 8,
    left: 35,
    width: 9,
    lag: 3,
    rotate: 20,
    opacity: 0.6,
  },
  {
    icon: <HalfFilledV2 color={Colors.Red} />,
    top: 21,
    left: -2,
    width: 13,
    lag: 1,
    rotate: -40,
  },
  {
    icon: <ArcOutline color={Colors.Beige} />,
    top: 20,
    left: -3,
    width: 13,
    lag: 3,
    rotate: -40,
  },
  {
    icon: <QuarterFilled color={Colors.Pink} />,
    top: 24,
    right: 10,
    width: 8,
    lag: 1,
  },
  {
    icon: <FullOutline color={Colors.Red} />,
    bottom: 9,
    right: 8,
    width: 9,
    lag: 4,
  },
  {
    icon: <FullFilled color={Colors.Purple} />,
    top: 14,
    right: 40,
    width: 8,
    lag: 1,
  },
  {
    icon: <HalfOutline color={Colors.Purple} />,
    top: 12,
    right: 40,
    width: 9,
    lag: 4,
    rotate: -180,
    opacity: 0.8,
  },
  {
    icon: <HalfFilledV2 color={Colors.Teal} />,
    bottom: 12,
    left: 8,
    width: 8,
    lag: 1,
    rotate: -180,
  },
  {
    icon: <FullOutline color={Colors.Teal} />,
    bottom: 10,
    left: 8,
    width: 6,
    lag: 4,
  },
  {
    icon: <HalfOutline color={Colors.Pink} />,
    top: 44,
    right: 30,
    width: 14,
    lag: 4,
    rotate: -32,
    opacity: 0.4,
  },
];

const contact: ShapeConfig[] = [
  {
    icon: <FullFilled color={Colors.Pink} />,
    bottom: 10,
    right: 18,
    width: 14,
    lag: 2,
    rotate: -32,
  },
  {
    icon: <FullOutline color={Colors.Pink} />,
    bottom: 10,
    right: 14,
    width: 14,
    lag: 4,
    rotate: -32,
  },
  {
    icon: <QuarterFilled color={Colors.Orange} />,
    top: 25,
    right: 14,
    width: 12,
    lag: 1,
    rotate: -132,
  },
  {
    icon: <HalfOutline color={Colors.Orange} />,
    top: 25,
    right: 16,
    width: 12,
    lag: 1,
    rotate: -70,
  },
  {
    icon: <HalfFilledV2 color={Colors.Teal} />,
    bottom: 20,
    left: 2,
    width: 10,
    lag: 1,
    rotate: 40,
  },
  {
    icon: <HalfOutline color={Colors.Teal} />,
    bottom: 20,
    left: 4,
    width: 12,
    lag: 1,
    rotate: 40,
    opacity: 0.6,
  },
  {
    icon: <ArcOutline color={Colors.Red} />,
    top: 20,
    left: 14,
    width: 14,
    lag: 3,
    rotate: 10,
    opacity: 0.6,
  },
  {
    icon: <FullOutline color={Colors.Red} />,
    top: 50,
    left: 40,
    width: 18,
    lag: 3,
    rotate: 10,
    opacity: 0.6,
  },
];

const projects: ShapeConfig[] = [
  {
    icon: <FullFilled color={Colors.Pink} />,
    top: 50,
    right: 40,
    width: 14,
    lag: 6,
    rotate: -32,
  },
  {
    icon: <FullOutline color={Colors.Pink} />,
    width: 14,
    top: 50,
    right: 36,
    lag: 1,
    rotate: -32,
  },
  {
    icon: <HalfFilledV2 color={Colors.Orange} />,
    bottom: 15,
    left: 14,
    width: 10,
    lag: 1,
    rotate: -132,
  },
  {
    icon: <HalfOutline color={Colors.Orange} />,
    bottom: 15,
    left: 16,
    width: 11,
    lag: 3,
    rotate: -120,
  },
  {
    icon: <HalfFilledV2 color={Colors.Teal} />,
    top: 30,
    right: 12,
    width: 10,
    lag: 1,
    rotate: -40,
  },
  {
    icon: <HalfOutline color={Colors.Teal} />,
    top: 30,
    right: 14,
    width: 12,
    lag: 4,
    rotate: -40,
    opacity: 0.6,
  },
  {
    icon: <ArcOutline color={Colors.Red} />,
    bottom: 20,
    right: 14,
    width: 14,
    lag: 3,
    rotate: 40,
    opacity: 0.6,
  },
  {
    icon: <FullOutline color={Colors.Red} />,
    top: 20,
    left: 10,
    width: 18,
    lag: 3,
    rotate: 10,
    opacity: 0.6,
  },
];

export { home, about, contact, projects };
